---
title: "Proposal"
output: html_document
---
# The tentative project title:
## Fantastic eats and where to find them

## Member:
Yutong Chen (yc4617),    
Tingcheng Pan (tp2859),     
Shiying Wu (sw3455)   
Yifan Xu (yx2857)    

## The motivation for this project:
It is hard for anyone to find a good restaurant, no matter if they stay in the same place for a long time or just move in like us. When people do not know where to eat, rating apps such as yelp would be a key resource for people to use. However, it led to an interesting question to us: what factors could correlate with rates or stars. 

## The intended final products:
An interactive `website` including tabs that include New York City restaurant map, top choices for a wonderful date,  specific dining scenarios like when you plan to take your furry friend or normal human, and how to earn higher ratings.

A detailed `R Markdown report` with data-driven analysis and visualizations, offering insights gained from our analysis and final results. The report will feature clear, reproducible code for accessible reading and understanding.

## The anticipated data sources:
Yelp data (https://www.yelp.com/dataset)

## The planned analyses / visualizations / coding challenges:
### The planned analyses:
1. How does review correlate with stars?   
2. Does the price range have higher quality with a higher star?   
3. What are the popular foods and important characteristics of restaurants for each state?    

### Visualizations:
1. Histogram about the restaurant distribution in each state
2. Scatter plot between review count and review quality
3. Histogram about the most popular types of restaurants (e.g., fast food, fine dining, cafes) by state or region.
4. Clustered scatter plot by location (cities or neighborhoods) and rating
5. Histogram about the distribution of price ranges by region
6. Interactive dashboard with filters to allow users to explore restaurants based on criteria like location, type, rating, and price.

### Coding challenges:
There are 58 columns of variables in the raw data from which we need to filter out the factors that have an impact on how good the restaurant is. We need to limit the database to restaurants in NYC. Because different restaurants upload differently and many categories are NAs, we need to do data cleaning. For such a large database, improving efficiency and finding accurate data is a major difficulty. Additionally, with limited experience in interactive visualizations, creating a reader-friendly dashboard from such a vast dataset will be a challenging learning experience.

## The planned timeline:
* 11/6-11/8: Written proposal    
* 11/9-11/10: Data reviewing, cleaning, further researching     
* 11/11-11/15: Review meeting with TA, and use advise for further analyze      
* 11/16-11/17: Website set up    
* 11/18-11/23: Data cleaning     
* 11/24-11/29: Data Analyst and Visualization      
* 11/30-12/4 : Finishing final draft and communicated with TA for any final touch     
* 12/5-12/6: Video Recording & Peer assessment     
* 12/7: Report Writing     
* 12/12: Presentation     

